// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class GestioneAlloggioTestCase3Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void gestioneAlloggioTestCase3() {
    // Test name: GestioneAlloggio_TestCase3
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    driver.get("http://localhost:5174/");
    // 2 | setWindowSize | 945x1020 |  | 
    driver.manage().window().setSize(new Dimension(945, 1020));
    // 3 | click | css=.sidebar-toggle-btn |  | 
    driver.findElement(By.cssSelector(".sidebar-toggle-btn")).click();
    // 4 | click | css=.menu-item > span |  | 
    driver.findElement(By.cssSelector(".menu-item > span")).click();
    // 5 | mouseOver | css=li:nth-child(2) span |  | 
    {
      WebElement element = driver.findElement(By.cssSelector("li:nth-child(2) span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 6 | click | linkText=Alloggi |  | 
    driver.findElement(By.linkText("Alloggi")).click();
    // 7 | click | css=.sidebar-overlay |  | 
    driver.findElement(By.cssSelector(".sidebar-overlay")).click();
    // 8 | click | css=.btn |  | 
    driver.findElement(By.cssSelector(".btn")).click();
    // 9 | click | css=.formField:nth-child(2) > input |  | 
    driver.findElement(By.cssSelector(".formField:nth-child(2) > input")).click();
    // 10 | type | css=.formField:nth-child(2) > input | c | 
    driver.findElement(By.cssSelector(".formField:nth-child(2) > input")).sendKeys("c");
    // 11 | type | css=textarea | ASA | 
    driver.findElement(By.cssSelector("textarea")).sendKeys("ASA");
    // 12 | click | css=.formField:nth-child(2) > input |  | 
    driver.findElement(By.cssSelector(".formField:nth-child(2) > input")).click();
    // 13 | type | css=.formField:nth-child(2) > input | Casa Bellissima | 
    driver.findElement(By.cssSelector(".formField:nth-child(2) > input")).sendKeys("Casa Bellissima");
    // 14 | click | id=root |  | 
    driver.findElement(By.id("root")).click();
    // 15 | type | css=textarea | Casa nel centro storico | 
    driver.findElement(By.cssSelector("textarea")).sendKeys("Casa nel centro storico");
    // 16 | click | css=select |  | 
    driver.findElement(By.cssSelector("select")).click();
    // 17 | select | css=select | label=WIFI | 
    {
      WebElement dropdown = driver.findElement(By.cssSelector("select"));
      dropdown.findElement(By.xpath("//option[. = 'WIFI']")).click();
    }
    // 18 | click | css=.formField:nth-child(5) > input |  | 
    driver.findElement(By.cssSelector(".formField:nth-child(5) > input")).click();
    // 19 | click | css=.formField:nth-child(6) > input |  | 
    driver.findElement(By.cssSelector(".formField:nth-child(6) > input")).click();
    // 20 | type | css=.formField:nth-child(6) > input | 100 | 
    driver.findElement(By.cssSelector(".formField:nth-child(6) > input")).sendKeys("100");
    // 21 | click | css=.formField:nth-child(5) > input |  | 
    driver.findElement(By.cssSelector(".formField:nth-child(5) > input")).click();
    // 22 | type | css=.formField:nth-child(5) > input | 3 | 
    driver.findElement(By.cssSelector(".formField:nth-child(5) > input")).sendKeys("3");
    // 23 | click | css=.formField:nth-child(8) > input |  | 
    driver.findElement(By.cssSelector(".formField:nth-child(8) > input")).click();
    // 24 | type | css=.formField:nth-child(8) > input | Via Garibaldi | 
    driver.findElement(By.cssSelector(".formField:nth-child(8) > input")).sendKeys("Via Garibaldi");
    // 25 | click | css=.formField:nth-child(9) > input |  | 
    driver.findElement(By.cssSelector(".formField:nth-child(9) > input")).click();
    // 26 | type | css=.formField:nth-child(9) > input | 101 | 
    driver.findElement(By.cssSelector(".formField:nth-child(9) > input")).sendKeys("101");
    // 27 | click | css=.formField:nth-child(10) > input |  | 
    driver.findElement(By.cssSelector(".formField:nth-child(10) > input")).click();
    // 28 | type | css=.formField:nth-child(10) > input | MontecorvinoRovella1000 | 
    driver.findElement(By.cssSelector(".formField:nth-child(10) > input")).sendKeys("MontecorvinoRovella1000");
    // 29 | click | css=.formField:nth-child(11) > input |  | 
    driver.findElement(By.cssSelector(".formField:nth-child(11) > input")).click();
    // 30 | type | css=.formField:nth-child(11) > input | 84096 | 
    driver.findElement(By.cssSelector(".formField:nth-child(11) > input")).sendKeys("84096");
    // 31 | click | css=.formField:nth-child(12) > input |  | 
    driver.findElement(By.cssSelector(".formField:nth-child(12) > input")).click();
    // 32 | type | css=.formField:nth-child(12) > input | SA | 
    driver.findElement(By.cssSelector(".formField:nth-child(12) > input")).sendKeys("SA");
    // 33 | click | css=button:nth-child(14) |  | 
    driver.findElement(By.cssSelector("button:nth-child(14)")).click();
    // 34 | mouseOver | css=button:nth-child(14) |  | 
    {
      WebElement element = driver.findElement(By.cssSelector("button:nth-child(14)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 35 | mouseOut | css=button:nth-child(14) |  | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
  }
}
