// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class GestioneAlloggioTestCase2Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void gestioneAlloggioTestCase2() {
    driver.get("http://localhost:5174/");
    driver.manage().window().setSize(new Dimension(945, 1020));
    driver.findElement(By.cssSelector(".sidebar-toggle-btn")).click();
    driver.findElement(By.cssSelector(".menu-item > span")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("li:nth-child(2) span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Alloggi")).click();
    driver.findElement(By.cssSelector(".sidebar-overlay")).click();
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".formField:nth-child(2) > input")).click();
    driver.findElement(By.cssSelector(".formField:nth-child(2) > input")).sendKeys("Casa Bellissima");
    driver.findElement(By.cssSelector("textarea")).click();
    driver.findElement(By.cssSelector("textarea")).sendKeys("Casa nel centro storico");
    driver.findElement(By.cssSelector("select")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector("select"));
      dropdown.findElement(By.xpath("//option[. = 'WIFI']")).click();
    }
    driver.findElement(By.cssSelector(".formField:nth-child(5) > input")).click();
    driver.findElement(By.cssSelector(".formField:nth-child(6) > input")).click();
    driver.findElement(By.cssSelector(".formField:nth-child(6) > input")).sendKeys("100");
    driver.findElement(By.cssSelector(".formField:nth-child(5) > input")).click();
    driver.findElement(By.cssSelector(".formField:nth-child(5) > input")).sendKeys("3");
    driver.findElement(By.cssSelector(".formField:nth-child(8) > input")).click();
    driver.findElement(By.cssSelector(".formField:nth-child(8) > input")).sendKeys("Via Garibaldi");
    driver.findElement(By.cssSelector(".formField:nth-child(9) > input")).click();
    driver.findElement(By.cssSelector(".formField:nth-child(9) > input")).sendKeys("27000");
    driver.findElement(By.cssSelector(".formField:nth-child(10) > input")).click();
    driver.findElement(By.cssSelector(".formField:nth-child(10) > input")).sendKeys("Montecorvino Rovella");
    driver.findElement(By.cssSelector(".formField:nth-child(11) > input")).click();
    driver.findElement(By.cssSelector(".formField:nth-child(11) > input")).sendKeys("84096");
    driver.findElement(By.cssSelector(".formField:nth-child(12) > input")).click();
    driver.findElement(By.cssSelector(".formField:nth-child(12) > input")).sendKeys("SA");
    driver.findElement(By.cssSelector(".formField:nth-child(13) > input")).click();
    driver.findElement(By.cssSelector("button:nth-child(14)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("button:nth-child(14)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
  }
}
