// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class GestioneAlloggioTestCase8Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void gestioneAlloggioTestCase8() {
    // Test name: GestioneAlloggio_TestCase8
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    driver.get("http://localhost:5174/");
    // 2 | setWindowSize | 945x1020 |  | 
    driver.manage().window().setSize(new Dimension(945, 1020));
    // 3 | click | css=.sidebar-toggle-btn |  | 
    driver.findElement(By.cssSelector(".sidebar-toggle-btn")).click();
    // 4 | click | css=.menu-item > span |  | 
    driver.findElement(By.cssSelector(".menu-item > span")).click();
    // 5 | click | linkText=Alloggi |  | 
    driver.findElement(By.linkText("Alloggi")).click();
    // 6 | click | css=.sidebar-overlay |  | 
    driver.findElement(By.cssSelector(".sidebar-overlay")).click();
    // 7 | click | css=.btn |  | 
    driver.findElement(By.cssSelector(".btn")).click();
    // 8 | click | css=.formField:nth-child(2) > input |  | 
    driver.findElement(By.cssSelector(".formField:nth-child(2) > input")).click();
    // 9 | type | css=.formField:nth-child(2) > input | Casa Bellissima | 
    driver.findElement(By.cssSelector(".formField:nth-child(2) > input")).sendKeys("Casa Bellissima");
    // 10 | click | css=textarea |  | 
    driver.findElement(By.cssSelector("textarea")).click();
    // 11 | type | css=textarea | @@@ | 
    driver.findElement(By.cssSelector("textarea")).sendKeys("@@@");
    // 12 | click | css=select |  | 
    driver.findElement(By.cssSelector("select")).click();
    // 13 | select | css=select | label=WIFI | 
    {
      WebElement dropdown = driver.findElement(By.cssSelector("select"));
      dropdown.findElement(By.xpath("//option[. = 'WIFI']")).click();
    }
    // 14 | click | css=.formField:nth-child(5) > input |  | 
    driver.findElement(By.cssSelector(".formField:nth-child(5) > input")).click();
    // 15 | type | css=.formField:nth-child(5) > input | 3 | 
    driver.findElement(By.cssSelector(".formField:nth-child(5) > input")).sendKeys("3");
    // 16 | click | css=.formField:nth-child(6) |  | 
    driver.findElement(By.cssSelector(".formField:nth-child(6)")).click();
    // 17 | click | css=.formField:nth-child(6) > input |  | 
    driver.findElement(By.cssSelector(".formField:nth-child(6) > input")).click();
    // 18 | type | css=.formField:nth-child(6) > input | 100 | 
    driver.findElement(By.cssSelector(".formField:nth-child(6) > input")).sendKeys("100");
    // 19 | click | css=.formField:nth-child(8) > input |  | 
    driver.findElement(By.cssSelector(".formField:nth-child(8) > input")).click();
    // 20 | type | css=.formField:nth-child(8) > input | Via Garibaldi | 
    driver.findElement(By.cssSelector(".formField:nth-child(8) > input")).sendKeys("Via Garibaldi");
    // 21 | click | css=.formField:nth-child(9) > input |  | 
    driver.findElement(By.cssSelector(".formField:nth-child(9) > input")).click();
    // 22 | type | css=.formField:nth-child(9) > input | 101 | 
    driver.findElement(By.cssSelector(".formField:nth-child(9) > input")).sendKeys("101");
    // 23 | click | css=.formField:nth-child(10) > input |  | 
    driver.findElement(By.cssSelector(".formField:nth-child(10) > input")).click();
    // 24 | type | css=.formField:nth-child(10) > input | Montecorvino Rovella | 
    driver.findElement(By.cssSelector(".formField:nth-child(10) > input")).sendKeys("Montecorvino Rovella");
    // 25 | click | css=.formContainer |  | 
    driver.findElement(By.cssSelector(".formContainer")).click();
    // 26 | click | css=.formField:nth-child(11) > input |  | 
    driver.findElement(By.cssSelector(".formField:nth-child(11) > input")).click();
    // 27 | type | css=.formField:nth-child(11) > input | 84096 | 
    driver.findElement(By.cssSelector(".formField:nth-child(11) > input")).sendKeys("84096");
    // 28 | click | css=.formField:nth-child(12) > input |  | 
    driver.findElement(By.cssSelector(".formField:nth-child(12) > input")).click();
    // 29 | type | css=.formField:nth-child(12) > input | SA | 
    driver.findElement(By.cssSelector(".formField:nth-child(12) > input")).sendKeys("SA");
    // 30 | click | css=.formField:nth-child(13) > input |  | 
    driver.findElement(By.cssSelector(".formField:nth-child(13) > input")).click();
    // 31 | click | css=button:nth-child(14) |  | 
    driver.findElement(By.cssSelector("button:nth-child(14)")).click();
    // 32 | runScript | window.scrollTo(0,485) |  | 
    js.executeScript("window.scrollTo(0,485)");
  }
}
