// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class BridgeTestLoginCorrettoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void bridgeTestLoginCorretto() {
    // Test name: BridgeTestLoginCorretto
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    driver.get("http://localhost:5174/");
    // 2 | setWindowSize | 788x864 |  | 
    driver.manage().window().setSize(new Dimension(788, 864));
    // 3 | click | css=.sidebar-toggle-btn |  | 
    driver.findElement(By.cssSelector(".sidebar-toggle-btn")).click();
    // 4 | click | css=.log-out > span |  | 
    driver.findElement(By.cssSelector(".log-out > span")).click();
    // 5 | type | id=email | volontario1@example.com | 
    driver.findElement(By.id("email")).sendKeys("volontario1@example.com");
    // 6 | type | id=password | Passroad69! | 
    driver.findElement(By.id("password")).sendKeys("Passroad69!");
    // 7 | click | css=.formButton |  | 
    driver.findElement(By.cssSelector(".formButton")).click();
  }
}
